name: Run Python Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  test:
    if: |
      !github.event.pull_request.head.repo.fork &&
      github.head_ref == 'develop'

    # GitHub runner
    runs-on: ubuntu-latest

    # Self-hosted runner
    # runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
      - run: |
          pytest test/test.py
